### ISSUE TITLE
一起搞赞乎

### ISSUE THREAD

**Issue by huotouyihao** [AllenYoungChina/zanhu#1]
加我qq：1192095698
留备注：github

**Comment by AllenYoungChina** [comment]
你好，如果你对这个项目感兴趣，请移步：https://coding.imooc.com/learn/list/333.html，支持原作者。
这里只是为了求职进行源码展示，稍后会删除该仓库。

**Comment by AllenYoungChina** [comment]
你好，如果你对该项目感兴趣，请移步：https://coding.imooc.com/class/333.html 支持该作者。
这里只是为了求职，展示代码，稍后会删除该仓库。
